-- Supabaseダッシュボードの SQL Editor で実行してください。
-- Latest単語モードを「クリア(全問正解)した日」を記録するテーブル。
-- localStorageではなくここに置くことで、複数ブラウザ・複数端末をまたいで
-- 連続達成日数を集計できるようにする。1日1行(同じ日に複数回クリアしても増えない)。
-- 読み取り専用anon + service_role書き込みの既存パターンをそのまま踏襲する。

create table if not exists public.latest_clears (
  id bigint generated by default as identity primary key,
  cleared_date date not null unique,
  created_at timestamptz not null default now()
);

alter table public.latest_clears enable row level security;

create policy "anon read-only"
  on public.latest_clears
  for select
  to anon
  using (true);
