-- Supabaseダッシュボードの SQL Editor で実行してください。
-- アプリの仕様・制約・今後の検討事項などを自由に書き留めておく「更改メモ」用テーブル。
-- words/expressionsとは完全に独立。読み取り専用anon + service_role書き込みの
-- 既存パターンをそのまま踏襲する。

create table if not exists public.notes (
  id bigint generated by default as identity primary key,
  text text not null,
  created_at timestamptz not null default now()
);

alter table public.notes enable row level security;

create policy "anon read-only"
  on public.notes
  for select
  to anon
  using (true);
