-- 英単語クイズ Supabaseテスト用スキーマ
-- 登山重量表テスト(SpabaseTest)と同じSupabaseプロジェクトに追加する。
-- Supabaseダッシュボード > SQL Editor で実行してください。

create table if not exists public.words (
  id bigint generated by default as identity primary key,
  row integer,
  en text not null,
  ja text not null,
  marker text, -- Excel Wrkシート D列由来。例: 'tips'。複数種のマーカーを今後追加予定
  created_at timestamptz not null default now()
);

create table if not exists public.expressions (
  id uuid primary key default gen_random_uuid(),
  ja text not null,
  en text not null,
  created_at timestamptz not null default now()
);

-- GitHub Pages等の公開環境にanonキーが出る前提で、anonロールは読み取り専用にする。
-- 書き込み(insert/update/delete)はservice_roleキーを持つローカルサーバー(server.js)経由でのみ行う。
alter table public.words enable row level security;
alter table public.expressions enable row level security;

create policy "anon read-only"
  on public.words
  for select
  to anon
  using (true);

create policy "anon read-only"
  on public.expressions
  for select
  to anon
  using (true);
